title: Climate Change Projections
description: What areas are as hot as the marker is? What areas are as hot right now as the marker will be in 2050 or 2070? Drag the marker to explore.

url: https://climatechange.codeforafrica.org
enforce_ssl: climatechange.codeforafrica.org

google_analytics: UA-44795600-29
